version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - ls -la .next/ || echo "Build output not found"
  post_build:
    commands:
      - npm install -g sonar-scanner
      - npx jest --coverage --coverageReporters=lcov
      - npx tsc --noEmit
      - sonar-scanner \
        -Dsonar.organization=$SONAR_ORGANIZATION \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.token=$SONAR_TOKEN_FRONT \
        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
        -Dsonar.inclusions=**/*.ts,**/*.tsx
artifacts:
  files:
    - '**/*'
  base-directory: '.next'
