name: Frontend Build with Sonar

on:
  push:
    branches: [main]
    paths:
      - 'new-app/**'  # S'exécute uniquement si des changements sont dans le dossier new-app
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - 'new-app/**'

env:
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new-app  # Définit le dossier de travail comme new-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Build Frontend
        run: npm run build
      - name: Check Build Output
        run: ls -la .next/ || echo "Build output not found"
